/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NationalRouteImport } from './routes/national'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KraRouteImport } from './routes/kra'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CrbRouteImport } from './routes/crb'
import { Route as CountiesRouteImport } from './routes/counties'
import { Route as IndexRouteImport } from './routes/index'

const NationalRoute = NationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KraRoute = KraRouteImport.update({
  id: '/kra',
  path: '/kra',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CrbRoute = CrbRouteImport.update({
  id: '/crb',
  path: '/crb',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesRoute = CountiesRouteImport.update({
  id: '/counties',
  path: '/counties',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counties': typeof CountiesRoute
  '/crb': typeof CrbRoute
  '/help': typeof HelpRoute
  '/kra': typeof KraRoute
  '/login': typeof LoginRoute
  '/national': typeof NationalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counties': typeof CountiesRoute
  '/crb': typeof CrbRoute
  '/help': typeof HelpRoute
  '/kra': typeof KraRoute
  '/login': typeof LoginRoute
  '/national': typeof NationalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counties': typeof CountiesRoute
  '/crb': typeof CrbRoute
  '/help': typeof HelpRoute
  '/kra': typeof KraRoute
  '/login': typeof LoginRoute
  '/national': typeof NationalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counties'
    | '/crb'
    | '/help'
    | '/kra'
    | '/login'
    | '/national'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/counties' | '/crb' | '/help' | '/kra' | '/login' | '/national'
  id:
    | '__root__'
    | '/'
    | '/counties'
    | '/crb'
    | '/help'
    | '/kra'
    | '/login'
    | '/national'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountiesRoute: typeof CountiesRoute
  CrbRoute: typeof CrbRoute
  HelpRoute: typeof HelpRoute
  KraRoute: typeof KraRoute
  LoginRoute: typeof LoginRoute
  NationalRoute: typeof NationalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/national': {
      id: '/national'
      path: '/national'
      fullPath: '/national'
      preLoaderRoute: typeof NationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kra': {
      id: '/kra'
      path: '/kra'
      fullPath: '/kra'
      preLoaderRoute: typeof KraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crb': {
      id: '/crb'
      path: '/crb'
      fullPath: '/crb'
      preLoaderRoute: typeof CrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties': {
      id: '/counties'
      path: '/counties'
      fullPath: '/counties'
      preLoaderRoute: typeof CountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountiesRoute: CountiesRoute,
  CrbRoute: CrbRoute,
  HelpRoute: HelpRoute,
  KraRoute: KraRoute,
  LoginRoute: LoginRoute,
  NationalRoute: NationalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
